import type { AppModule } from '../types/modules';

export const APP_MODULES: AppModule[] = [
  {
    id: 'timeBlindness',
    name: 'Time Awareness',
    shortName: 'Time',
    description: 'Tools to help you stay aware of passing time, set visual timers, and build a better sense of duration.',
    icon: 'time-outline',
    colorKey: 'timeBlindness',
    route: '/(protected)/time-blindness',
  },
  {
    id: 'finance',
    name: 'Money Manager',
    shortName: 'Money',
    description: 'Track expenses fast, manage a weekly budget, and set gentle bill reminders.',
    icon: 'wallet-outline',
    colorKey: 'finance',
    route: '/(protected)/finance',
  },
  {
    id: 'tasks',
    name: 'Task Pilot',
    shortName: 'Tasks',
    description: 'Break down large tasks, protect your top 3 focus items, and sort priorities clearly.',
    icon: 'checkbox-outline',
    colorKey: 'tasks',
    route: '/(protected)/tasks',
  },
  {
    id: 'memory',
    name: 'Remember Well',
    shortName: 'Memory',
    description: 'Capture thoughts quickly, schedule reminders, and close loops with daily recap prompts.',
    icon: 'bulb-outline',
    colorKey: 'memory',
    route: '/(protected)/memory',
  },
  {
    id: 'dopamine',
    name: 'Motivation Boost',
    shortName: 'Motivate',
    description: 'Use activation prompts, energy modes, and streaks to build reliable momentum.',
    icon: 'sparkles-outline',
    colorKey: 'dopamine',
    route: '/(protected)/dopamine',
  },
  {
    id: 'speech',
    name: 'Clear Voice',
    shortName: 'Speech',
    description: 'Plan conversations, draft messages, and practice paced delivery for clearer communication.',
    icon: 'chatbubble-ellipses-outline',
    colorKey: 'speech',
    route: '/(protected)/speech',
  },
  {
    id: 'thoughts',
    name: 'Thought Organizer',
    shortName: 'Thoughts',
    description: 'Brain-dump fast, tag thought types, and complete wind-down reflections with next steps.',
    icon: 'cloud-outline',
    colorKey: 'thoughts',
    route: '/(protected)/thoughts',
  },
  {
    id: 'impulse',
    name: 'Pause & Reflect',
    shortName: 'Impulse',
    description: 'Use pause timers, if-then prompts, and trigger reflection logs to act with intention.',
    icon: 'hand-left-outline',
    colorKey: 'impulse',
    route: '/(protected)/impulse',
  },
];
